name: Deploy on Push

on:
  push:
    branches: [ main ]  # Change "main" to your deployment branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: build  # The build output folder
          target: /anujjbubna.github.io/BabysDayOut  # Replace with your username and repo name
          single-branch: true  # Optional: Only deploy on push to the specified branch


